apiVersion: v1
kind: Service
metadata:
  name: cluster-example-nodeport
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: cluster-example
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
