apiVersion: v1
kind: Pod
metadata:
  name: psql-client-tls
spec:
  restartPolicy: Never
  containers:
  - name: psql
    image: postgres:13
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: tls-secret
      mountPath: /tls
      readOnly: true
  volumes:
  - name: tls-secret
    secret:
      secretName: cluster-example-server-tls
