apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-example-server-tls
spec:
  secretName: cluster-example-server-tls
  commonName: cluster-example.default.svc
  dnsNames:
    - cluster-example
    - cluster-example.default
    - cluster-example.default.svc
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
